"""Add_AI_Fields

Revision ID: 5f72c9a24bd4
Revises: a97a2dc91791
Create Date: 2026-04-06 01:35:53.126046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f72c9a24bd4'
down_revision: Union[str, None] = 'a97a2dc91791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('risk_score', sa.Float(), nullable=True))
    op.add_column('alerts', sa.Column('is_voice_triggered', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'is_voice_triggered')
    op.drop_column('alerts', 'risk_score')
    # ### end Alembic commands ###
